# This example uses yaml anchors which allows to name keys
# and re-use for multiple keys in a flexible way.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example
keys:
  - &admin AB7F4A02A3586B6879BB666AA3880C94A8F40F52
  - &car ab7f20de23259cb619b15c2f695369c73c14c778
  - &cadr a0fdd32e99a61d094c3f872225b7fc9517b66ae7
  - &fb e14ad9a8f43f0399403cd0e25347660b9803f3a5
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *admin
      - *car
      - *cadr
      - *fb
