# This example uses yaml anchors which allows to name keys
# and re-use for multiple keys in a flexible way.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example
keys:
  - &admin AB7F4A02A3586B6879BB666AA3880C94A8F40F52
  - &car 9d12ecb82d1856c717b25c7271f4c324fdea0e13
  - &cadr 53e15eddba0a72ef282a8b7bd9f31942ddc7f65b
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *admin
      - *car
      - *cadr
